spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true

jwt:
  issuer: lost-item-reporting